source 'https://supermarket.chef.io'

metadata

cookbook 'windows', '~> 1.37.0'
cookbook 'iis', '~> 4.1.1'
cookbook 'chocolatey', '~> 0.3.0'

cookbook 'nodejs-windows', '~> 0.10.13'

cookbook 'visualstudio', git: 'https://github.com/TattsGroup/cookbook-visualstudio'
