# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.winrm.port = 5985
  config.winrm.guest_port = 5985

  config.winrm.username = Secret.winrm_username
  config.winrm.password = Secret.winrm_password

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.guest = :windows
  config.vm.communicator = :winrm

  config.omnibus.chef_version = '12.4.1'

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "../chef-repo/Berksfile"

  config.vm.provider "vmware_fusion" do |v|
    v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"

    v.vmx["ethernet0.virtualDev"] = "e1000"
    v.vmx["ethernet0.connectionType"] = "bridged"
    v.vmx["ethernet0.startConnected"] = "true"
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    # config.proxy.http     = "http://192.168.0.2:3128/"
    # config.proxy.https    = "http://192.168.0.2:3128/"
    # config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end

  config.vm.provision "windowsupdate", type: "shell" do |s|
    s.path = "scripts/windowsupdate-disable.ps1"
  end

  config.vm.define "buildagent", autostart: true do |node|
    node.vm.box = "windows-2012r2-20150813"
    node.vm.hostname = "buildagent"

    node.hostmanager.aliases = %w(buildagent.devops)

    ## this makes things easier, but it's not useful for future proofing
    ## node.vm.synced_folder "~/Desktop/ISO/", "/Install"

    node.vm.provision "chef", type: "chef_solo" do |chef|
      chef.cookbooks_path    = "../chef-repo/cookbooks"
      chef.data_bags_path    = "../chef-repo/data_bags"
      chef.roles_path        = "../chef-repo/roles"

      # chef.add_role "teamcityagent"
      chef.add_role "developer"
      # chef.add_role "sqlserver"
      # chef.add_role "octopusserver"

      # chef.add_recipe "powershell::powershell5"
      # chef.add_recipe "octopus::create_environment"
      # chef.add_recipe "octopus::register_tentacle"

      chef.json = {
        :java => {
          :windows => {
            :url => "http://10.0.1.59/jre-8u51-windows-x64.exe",
            :checksum => "3895872bc4cdfb7693c227a435cf6740f968e4fa6ce0f7449e6a074e3e3a0f01",
            :package_name => "Java 8 Update 51 (64-bit)"
          }
        },
        :teamcity => {
          :agent => {
            :name => "buildagent",
            :server_uri => "http://teamcity.devops:8111",
            :system_dir => "c:/teamcity",
            :work_dir => "c:/teamcity/work",
            :temp_dir => "c:/teamcity/temp"
          }
        },
        :sqlserver => {
          :source => "http://10.0.1.60"
        },
        :visualstudio => {
          :source => "http://10.0.1.60"
        },
        :nodejs => {
          :url => "http://10.0.1.60/node-v0.12.7-x86.msi"
        },
        :runtime => {
          :vc2013 => {
            :url => "http://10.0.1.60/vc_redis.2013.x64.exe",
            :checksum => "e554425243e3e8ca1cd5fe550db41e6fa58a007c74fad400274b128452f38fb8"
          },
          :vc2105 => {
            :url => "http://10.0.1.60/vc_redis.2015.x64.exe",
            :checksum => "5eea714e1f22f1875c1cb7b1738b0c0b1f02aec5ecb95f0fdb1c5171c6cd93a3"
          }
        },
        :powershell => {
          :powershell5 => {
            :url => "http://10.0.1.60/WindowsBlue-KB3037315-x64.msu",
            :checksum => "9a24de7b85fae96a87188a7fdaab27da3bc90d89426594cdc5f962234a61b7bd"
          }
        },
        :octopus => {
          :tentacle => {
            :url => "http://10.0.1.60/Octopus.Tentacle.3.0.13.2386-x64.msi",
            :checksum => "ec49dfa9d05016098a3ff4d9b4df6b42a92934e87e4518de2a4c35b46fa3f89c",
            :environment => "development",
            :roles => %w( "web" "api" "database" )
          },
          :api => {
            :uri => "http://octopus.devops/api",
            :key => "API-ZVWYPPD55HV5AALOXOVANBOZMU"
          },
          :server => {
            :thumbprint => "F22074CC456CEB845E258824A0B522932B7A6F95"
          }
        }
      }
    end
  end
end
