# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.winrm.port = 5985
  config.winrm.guest_port = 5985

  config.winrm.username = Secret.winrm_username
  config.winrm.password = Secret.winrm_password

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.guest = :windows
  config.vm.communicator = :winrm

  config.omnibus.chef_version = '12.4.1'

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "chef-repo/Berksfile"

  config.vm.provider "vmware_fusion" do |v|
    v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"

    v.vmx["ethernet0.virtualDev"] = "e1000"
    v.vmx["ethernet0.connectionType"] = "bridged"
    v.vmx["ethernet0.startConnected"] = "true"
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    # config.proxy.http     = "http://192.168.0.2:3128/"
    # config.proxy.https    = "http://192.168.0.2:3128/"
    # config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end

  config.vm.provision "windowsupdate", type: "shell" do |s|
    s.path = "scripts/windowsupdate-disable.ps1"
  end

  config.vm.define "buildagent", autostart: true do |node|
    node.vm.box = "windows-2012r2-20150812"
    node.vm.hostname = "buildagent"

    node.hostmanager.aliases = %w(buildagent.devops)

    ## this makes things easier, but it's not useful for future proofing
    ## node.vm.synced_folder "~/Desktop/ISO/", "/Install"

    node.vm.provision "chef", type: "chef_solo" do |chef|
      chef.cookbooks_path    = "chef-repo/cookbooks"
      chef.data_bags_path    = "chef-repo/data_bags"
      chef.roles_path        = "chef-repo/roles"

      chef.add_role "teamcityagent"
      chef.add_role "developer"

      # chef.add_recipe "octopus::install_tentacle"
      # chef.add_recipe "octopus::create_environment"
      # chef.add_recipe "octopus::register_tentacle"

      chef.json = {
        :java => {
          :windows => {
            :url => "http://10.0.1.59/jre-8u51-windows-x64.exe",
            :checksum => "3895872bc4cdfb7693c227a435cf6740f968e4fa6ce0f7449e6a074e3e3a0f01",
            :package_name => "Java 8 Update 51 (64-bit)"
          }
        },
        :teamcity => {
          :agent => {
            :name => "buildagent",
            :server_uri => "http://10.0.1.2:8111",
            :system_dir => "c:/teamcity",
            :work_dir => "c:/teamcity/work",
            :temp_dir => "c:/teamcity/temp"
          }
        },
        :visualstudio => {
          :source => "http://10.0.1.59"
        },
        :nodejs => {
          :url => "http://10.0.1.59/node-v0.12.7-x86.msi"
        },
        :octopus => {
          :tentacle => {
            :url => "https://download.octopusdeploy.com/octopus/Octopus.Tentacle.3.0.12.2366-x64.msi",
            :checksum => "8503e00959e21feec72c84e6a245e6a59c3775d14d2fc1ce07e64c8d5a5eafea",
            :environment => "development",
            :role => "api",
            :name => "server01"
          },
          :api => {
            :uri => "http://10.0.1.51/api",
            :key => "API-ZVWYPPD55HV5AALOXOVANBOZMU"
          },
          :server => {
            :thumbprint => "F22074CC456CEB845E258824A0B522932B7A6F95"
          }
        }
      }
    end
  end
end
