# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.boot_timeout = 1000
  config.vm.box = 'azure'

  config.omnibus.chef_version = :latest

  config.vm.provider :azure do |azure|
    azure.mgmt_endpoint = 'https://management.core.windows.net'
    azure.mgmt_certificate = Secret.azure_mgmt_certificate
    azure.subscription_id = Secret.azure_subscription_id

    azure.storage_acct_name = 'azurevagrantstorage'
    azure.cloud_service_name = 'azurevagrant-service'

    azure.vm_image = 'a699494373c04fc0bc8f2bb1389d6106__Windows-Server-2012-R2-201504.01-en.us-127GB.vhd'
    azure.vm_user = Secret.azure_vm_user
    azure.vm_password = Secret.azure_vm_password

    azure.vm_location = 'West US'

    azure.vm_name = 'azurevagrant'
    azure.tcp_endpoints = '3389:53389'

    azure.winrm_transport = [ 'http', 'https' ] # this will open up winrm ports on both http (5985) and http (5986) ports

    azure.winrm_https_port = '15985'
    azure.winrm_http_port = '15986'
  end

  config.vm.provision "chocolatey", type: "shell" do |s|
    s.inline = [ 
      "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))",
      "choco feature enable -n=allowGlobalConfirmation"
    ]
  end

  config.vm.provision "chef", type: "shell" do |s|
    s.inline = "choco install chef-client"
  end
end
