# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.winrm.port = 5985
  config.winrm.guest_port = 5985

  config.winrm.username = "packer"
  config.winrm.password = "packer"

  config.hostmanager.enabled = false
  config.hostmanager.manage_host = false

  config.vm.guest = :windows
  config.vm.communicator = :winrm

  config.vm.provider "vmware_fusion" do |v|
    v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end  

  config.vm.define "impressive", autostart: true do |node|
    node.vm.box = "impressive"
    node.vm.hostname = "impressive"

    #node.vm.network :public_network, bridge: "en0"
  end
end
