---
driver:
  name: vagrant
  gui: true
  provider: vmware_fusion

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2-20150813
  - name: windows-2012r2core-20150816

suites:
  - name: server
    run_list:
      - recipe[octopus3::server]
    attributes:
      octopus:
        server:
          connectionstring: "Data Source=10.0.1.93;Initial Catalog=OctopusDeploy;Integrated Security=True"
          admin_user: "packer"
      sqlserver:
        source: "http://10.0.1.59"
  - name: tentacle
    run_list:
      - recipe[octopus3::tentacle]
    attributes:
      octopus:
        api:
          url: "http://10.0.1.89/api"
          key: "API-MDVAVSM6OYVBEORDCKLVGZZNUO"
        server:
          url: "http://10.0.1.89"
          thumbprint: "ACC5880A119A7FBCA4899D1562ED1E52876C9E1A"
        tentacle:
          environments: "\"Kitchen\", \"DevOps\""
          roles: "\"web\", \"api\", \"database\""
