name 'octopus3'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures octopus3'
long_description 'Installs/Configures octopus3'
version '0.1.0'

depends 'windows'
depends 'windows_firewall'
depends 'powershell'
