source "https://supermarket.chef.io"

cookbook "devops", path: "cookbooks/devops"
cookbook "sqlserver", path: "cookbooks/sqlserver"

cookbook "role-baseserver", path: "cookbooks/role-baseserver"
cookbook "role-octopusserver", path: "cookbooks/role-octopusserver"
cookbook "role-teamcityagent", path: "cookbooks/role-teamcityagent"
cookbook "role-developer", path: "cookbooks/role-developer"

cookbook 'octopus', '~> 0.1.3'

cookbook "seven_zip", github: "daptiv/seven_zip"
cookbook "dotnetframework", github: "daptiv/dotnetframework"
cookbook "visualstudio", github: "TattsGroup/cookbook-visualstudio", branch: "vs2015"

