source "https://supermarket.chef.io"

cookbook "devops", path: "cookbooks/devops"

cookbook "role-baseserver", path: "cookbooks/role-baseserver"
cookbook "role-octopusserver", path: "cookbooks/role-octopusserver"
cookbook "role-teamcityagent", path: "cookbooks/role-teamcityagent"

cookbook 'octopus',  git: 'https://github.com/Zeroto/octopus-cookbook.git'
