# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.winrm.port = 5985
  config.winrm.guest_port = 5985

  config.winrm.username = Secret.winrm_username
  config.winrm.password = Secret.winrm_password

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.guest = :windows
  config.vm.communicator = :winrm

  # node.vm.network :forwarded_port,   guest: 3389, host: 3389,       id: "rdp",       auto_correct: true
  # node.vm.network :forwarded_port,   guest: 5985, host: 5985,       id: "winrm",     auto_correct: true

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "chef-repo/Berksfile"

  config.vm.provider "vmware_fusion" do |v|
    v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"

    v.vmx["ethernet0.virtualDev"] = "e1000"
    #v.vmx["ethernet0.connectionType"] = "bridged"
    #v.vmx["ethernet0.startConnected"] = "true"
  end  

  if Vagrant.has_plugin?("vagrant-proxyconf")
    # config.proxy.http     = "http://192.168.0.2:3128/"
    # config.proxy.https    = "http://192.168.0.2:3128/"
    # config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end

  config.vm.provision "windowsupdate", type: "shell" do |s|
    s.path = "scripts/windowsupdate-disable.ps1"
  end

  config.vm.provision "chocolatey", type: "shell" do |s|
    s.path = "scripts/chocolatey-cache.ps1"
  end

  config.vm.provision "wmf5", type: "shell" do |s|
    s.path = "scripts/powershell-wmf5.ps1"
  end

  config.vm.define "octopus", autostart: false do |node|
    node.vm.box = "server2012r2_20150725.1"
    node.vm.hostname = "octopus.devops"

    node.vm.provision "chef", type: "chef_solo" do |chef|
      chef.cookbooks_path    = "chef-repo/cookbooks"
      chef.data_bags_path    = "chef-repo/data_bags"
      chef.environments_path = "chef-repo/environments"
      chef.roles_path        = "chef-repo/roles"

      chef.add_role "octopusserver"
      # chef.add_role "teamcityagent"
    end
  end

  config.vm.define "server", autostart: false do |node|
    node.vm.box = "server2012r2_20150725.1"
    node.vm.hostname = "server"

    node.vm.provision "chef", type: "chef_solo" do |chef|
      chef.cookbooks_path    = "chef-repo/cookbooks"
      chef.data_bags_path    = "chef-repo/data_bags"
      chef.environments_path = "chef-repo/environments"
      chef.roles_path        = "chef-repo/roles"

      chef.add_role "baseserver"
    end
  end

  config.vm.define "developer", autostart: true do |node|
    node.vm.box = "server2012r2_20150725.1"
    node.vm.hostname = "developer"

    node.hostmanager.aliases = %w(developer.devops)

    node.vm.provision "chef", type: "chef_solo" do |chef|
      chef.cookbooks_path    = "chef-repo/cookbooks"
      chef.data_bags_path    = "chef-repo/data_bags"
      chef.environments_path = "chef-repo/environments"
      chef.roles_path        = "chef-repo/roles"

      chef.add_role "baseserver"
      chef.add_role "developer"
    end
  end
end
