source "https://supermarket.chef.io"

cookbook "role-baseserver", path: "cookbooks/role-baseserver"
cookbook "role-octopusserver", path: "cookbooks/role-octopusserver"
cookbook "role-teamcityagent", path: "cookbooks/role-teamcityagent"
cookbook "role-developer", path: "cookbooks/role-developer"

cookbook 'octopus', github: "TattsGroup/cookbook-octopus", branch: "certificate_if_blank"

cookbook "visualstudio", github: "TattsGroup/cookbook-visualstudio", branch: "remove_sevenzip"
