# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.winrm.port = 5985
  config.winrm.guest_port = 5985

  config.winrm.username = Secret.winrm_username
  config.winrm.password = Secret.winrm_password

  config.hostmanager.enabled = false
  config.hostmanager.manage_host = false
  config.hostmanager.include_offline = true

  config.vm.box = "../boxes/windows_2012_r2-1.0.8.box"

  config.vm.hostname = "octopus"

  config.vm.guest = :windows
  config.vm.communicator = :winrm
  config.vm.network :public_network

  config.vm.network :forwarded_port,   guest: 3389, host: 3389,       id: "rdp",   auto_correct: false
  config.vm.network :forwarded_port,   guest: 5985, host: 5985,       id: "winrm", auto_correct: false

  config.omnibus.chef_version = :latest
  config.omnibus.cache_packages = true
  config.cache.scope = :box

  config.vm.provider "vmware_fusion" do |v|
    v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
    v.vmx["ethernet0.virtualDev"] = "e1000"
    v.vmx["ethernet0.connectionType"] = "nat"
    v.vmx["gui.fitguestusingnativedisplayresolution"] = "FALSE"
  end  

  config.vm.provision "noproxy", type: "shell" do |s|
    s.path = "scripts/proxy-disable.ps1"
  end
 
  config.vm.provision "chocolatey", type: "shell" do |s|
    s.path = "scripts/chocolatey-cache.ps1"
  end

  config.vm.provision "wmf5", type: "shell" do |s|
    s.path = "scripts/powershell-wmf5.ps1"
  end

  config.vm.provision "psget", type: "shell" do |s|
    s.path = "scripts/powershell-psget.ps1"
  end

  config.vm.provision "chefinstall", type: "shell" do |s|
    s.inline = "choco install chef-client"
  end
end
