name             'devops'
maintainer       'Shaw Innes'
maintainer_email 'shaw@immortal.net.au'
license          'All rights reserved'
description      'Installs/Configures devops'
long_description 'Installs/Configures devops'
version          '0.1.2'

depends          'windows'
depends          'iis'
depends          'chocolatey'
depends          'octopus'
depends          'windows_firewall'
