name             'role-developer'
maintainer       'Shaw Innes'
maintainer_email 'shaw@immortal.net.au'
license          'All rights reserved'
description      'Installs/Configures Developer Machine'
long_description 'Installs/Configures Developer Machine'
version          '0.1.1'

depends          'windows'
depends          'iis'
depends          'chocolatey'
