# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "vmware_fusion" do |v|
    v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end 

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.define "teamcity", autostart: true do |node|
    node.vm.hostname = "teamcity.devops"

    node.vm.box = "hashicorp/precise64"
    # node.vm.network :forwarded_port, guest: 8111, host: 9000
    node.vm.network :public_network, bridge: "en0"

    node.vm.provision "base", type: "shell" do |s|
$script = <<SCRIPT 
  sudo apt-get update -y
  sudo apt-get install openjdk-7-jre-headless -y
SCRIPT

      s.inline = $script
    end

    node.vm.provision "teamcity", type: "shell" do |s|
$script = <<SCRIPT 
  tar -xvzf /vagrant/TeamCity-9.0.4.tar.gz

  export TEAMCITY_DATA_PATH=\"/var/TeamCity/.BuildServer\"

  sudo mkdir -p /home/vagrant/TeamCity/logs
  sudo chown vagrant:vagrant -R /home/vagrant/TeamCity/

  /home/vagrant/TeamCity/bin/teamcity-server.sh start
SCRIPT

      s.inline = $script
    end
  end

end
