name             'role-teamcityagent'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures role-teamcityagent'
long_description 'Installs/Configures role-teamcityagent'
version          '0.1.0'

depends          'chocolatey'
depends          'chef-teamcity'
depends          'nodejs-windows'
