# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  config.vm.hostname = "chefserver.devops"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.provision "baseinstall", type: "shell", inline: <<-SHELL
    ## sudo apt-get update
    sudo dpkg -i /vagrant/packages/chef-server-core_12.1.0-1_amd64.deb
  SHELL

  config.vm.provision "reconfigure", type: "shell", inline: <<-SHELL
    sudo chef-server-ctl reconfigure
  SHELL

  config.vm.provision "init", type: "shell", inline: <<-SHELL
    sudo chef-server-ctl user-create chefadmin "Chef Admin" chefadmin@chefserver.devops Password01 --filename chefadmin.pem
    sudo chef-server-ctl org-create chefdemo "Chef Demo" --association chefadmin --filename chefdemo-validator.pem

    cp chefadmin.pem /vagrant
    cp chefdemo-validator.pem /vagrant
  SHELL

  config.vm.provision "webui", type: "shell", inline: <<-SHELL
    sudo sudo chef-server-ctl install opscode-manage
    sudo opscode-manage-ctl reconfigure
    sudo chef-server-ctl reconfigure
  SHELL
end
