source "https://supermarket.chef.io"

cookbook "apt"
cookbook 'graphite', '~> 1.0.2'
cookbook 'grafana', '~> 1.5.5'
cookbook "vim"
 
cookbook "statsd",
  :git => "https://github.com/hectcastro/chef-statsd",
  :ref => "v1.1.3"
