---
driver:
  name: vagrant
  gui: true
  provider: vmware_fusion

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2-20150812

suites:
  - name: default
    run_list:
      - recipe[role-sqlserver::default]
    attributes:
